MINOR: README: add warning about comma in value string
When using helm cli  with `--set` parameters, one also need to escape
commas ',' in the value string, such as:

helm upgrade syslog haproxytech/kubernetes-ingress \
  --set controller.config."syslog-server"="address:127.0.0.1\, facility:local0\, format:raw\, level:notice"

otherwise such error is returned:
  Error: failed parsing --set data: key " format:raw, level:notice" has no value