fix(haproxy): ci error for instaliing haproxy chart.
Hi, team.
I fixed CI error due to [this PR](feat: allow to set several probe more freely.).
CI error is bellow:
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0].startupProbe): unknown field "enabled" in io.k8s.api.core.v1.Probe
```

Signed-off-by: mugioka <okamugi0722@gmail.com>